### ISSUE TITLE
In ShowName and ShowText function, GetBackCDC is repeated code. Need to be fixed

### ISSUE THREAD

**Issue by 2021Vincent** [kyynk/ao_oni#45]
void Dialog::ShowText() {
		CDC* pDC = CDDraw::GetBackCDC();
		CTextDraw::ChangeFontLog(pDC, 20, "Noto Sans TC", RGB(255, 255, 255));
		for (int i = 0; i < int(_store.size()); i++) {
			CTextDraw::Print(pDC, _txtX, _txtY + i * _lineSpacing, _store.at(i));
		}
		CDDraw::ReleaseBackCDC();
	}
	void Dialog::ShowNameBox() {
		_nameBox.SetTopLeft(_nBoxX, _nBoxY);
		_nameBox.ShowBitmap();
	}
	void Dialog::ShowName() {
		CDC* pDC = CDDraw::GetBackCDC();
		CTextDraw::ChangeFontLog(pDC, 20, "Noto Sans TC", RGB(152, 245, 255));
		CTextDraw::Print(pDC, _nameX, _nameY, _name.at(_now));
		CDDraw::ReleaseBackCDC();
	}

**Comment by kyynk** [comment]
這個是因為名字跟對話內容在的位子不一樣
所以我把它分兩個寫

**Comment by kyynk** [comment]
issue fixed

**Comment by kyynk** [comment]
分開圖片和文字的顯示之後 ( 把 ShowText(CDC *pDC) 移開 ShowTotal() )
讓ShowText()從game_run的地方傳入CDC *pDC
就沒問題了
