### ISSUE TITLE
Item::OnMove

### ISSUE THREAD

**Issue by 2021Vincent** [kyynk/ao_oni#58]
`void Item::OnMove(UINT nChar) {
		if (Collide()) {
			if (nChar == 0x47)
				_close = true;
			if (_move == isright && nChar == VK_RIGHT)
				_pos_x += _step;
			else if (_move == isleft && nChar == VK_LEFT)
				_pos_x -= _step;
			else if (_move == isup && nChar == VK_UP)
				_pos_y -= _step;
			else if (_move == isdown && nChar == VK_DOWN)
				_pos_y += _step;
		}
		bitmap.SetTopLeft(_pos_x, _pos_y);
	}`
OnMove的On在先前的版本沒有，加上On是想強調會隨著時間更新。
OnMove不應該接KEY nChar，這是OnkeyUp/OnkeyDown要處理的事情
應該將控制移動和偵測按鍵的責任分開

**Comment by kyynk** [comment]
ok

**Comment by kyynk** [comment]
fixed issue
